# Generated by Django 4.2.6 on 2023-10-28 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_cliente_trazabilidad_maquinaria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maquinaria',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='maquinaria',
            name='n_orden',
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='maquinaria',
            name='historial',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='trazabilidad',
            name='maquinaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.maquinaria'),
        ),
        migrations.AddField(
            model_name='trazabilidad',
            name='n_orden',
            field=models.CharField(default='NULL', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='maquinaria',
            name='año',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='maquinaria',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maquinarias', to='myapp.cliente'),
        ),
        migrations.AlterUniqueTogether(
            name='trazabilidad',
            unique_together={('cliente', 'maquinaria')},
        ),
        migrations.RemoveField(
            model_name='trazabilidad',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='trazabilidad',
            name='n_oreden',
        ),
    ]
