# Generated by Django 4.2.6 on 2023-10-28 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_maquinaria_marca_remove_maquinaria_n_orden_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trazabilidad',
            name='maquinaria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.maquinaria'),
        ),
    ]
