# Generated by Django 4.2.6 on 2023-10-28 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_trazabilidad_maquinaria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='trazabilidad',
            name='maquinaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.maquinaria'),
        ),
        migrations.AlterField(
            model_name='trazabilidad',
            name='n_orden',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
