# Generated by Django 4.2.6 on 2023-10-28 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_cliente_telefono_alter_trazabilidad_maquinaria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trazabilidad',
            name='maquinaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.maquinaria'),
        ),
    ]
