# Generated by Django 4.2.6 on 2023-11-11 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_trazabilidad_maquinaria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquinaria',
            name='cliente',
            field=models.CharField(max_length=100),
        ),
    ]
