# Generated by Django 4.2.6 on 2023-11-11 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_maquinaria_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trazabilidad',
            name='cliente',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='trazabilidad',
            name='maquinaria',
            field=models.CharField(max_length=100),
        ),
    ]
