# Generated by Django 4.2.6 on 2023-11-15 15:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_trazabilidad_cliente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NOMBRE_MANUAL', models.CharField(max_length=100)),
                ('TIPO_MANUAL', models.CharField(max_length=100)),
                ('AÑO_MANUAL', models.PositiveIntegerField()),
                ('PDF_MANUAL', models.FileField(upload_to='pdfs/')),
            ],
        ),
        migrations.RenameField(
            model_name='maquinaria',
            old_name='año',
            new_name='AÑO',
        ),
        migrations.RenameField(
            model_name='maquinaria',
            old_name='cliente',
            new_name='CLIENTE',
        ),
        migrations.RenameField(
            model_name='maquinaria',
            old_name='cotizacion',
            new_name='MAQUINARIA',
        ),
        migrations.RenameField(
            model_name='maquinaria',
            old_name='modelo',
            new_name='MARCA',
        ),
        migrations.RenameField(
            model_name='maquinaria',
            old_name='n_serie',
            new_name='ORDEN',
        ),
        migrations.RenameField(
            model_name='maquinaria',
            old_name='historial',
            new_name='PROBLEMA',
        ),
        migrations.RenameField(
            model_name='trazabilidad',
            old_name='descripcion',
            new_name='descripcion_problema',
        ),
        migrations.RenameField(
            model_name='trazabilidad',
            old_name='tipo',
            new_name='marca',
        ),
        migrations.AlterUniqueTogether(
            name='trazabilidad',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='maquinaria',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='maquinaria',
            name='FECHA',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trazabilidad',
            name='año',
            field=models.PositiveIntegerField(default=2023),
            preserve_default=False,
        ),
    ]
