# Generated by Django 4.2.6 on 2023-11-17 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_manual_rename_año_maquinaria_año_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manual',
            old_name='AÑO_MANUAL',
            new_name='año_manual',
        ),
        migrations.RenameField(
            model_name='manual',
            old_name='NOMBRE_MANUAL',
            new_name='nombre_manual',
        ),
        migrations.RenameField(
            model_name='manual',
            old_name='PDF_MANUAL',
            new_name='pdf_manual',
        ),
        migrations.RenameField(
            model_name='manual',
            old_name='TIPO_MANUAL',
            new_name='tipo_manual',
        ),
        migrations.RenameField(
            model_name='maquinaria',
            old_name='AÑO',
            new_name='año',
        ),
        migrations.RenameField(
            model_name='maquinaria',
            old_name='CLIENTE',
            new_name='cliente',
        ),
        migrations.RenameField(
            model_name='maquinaria',
            old_name='FECHA',
            new_name='fecha',
        ),
        migrations.RenameField(
            model_name='maquinaria',
            old_name='MAQUINARIA',
            new_name='maquinaria',
        ),
        migrations.RenameField(
            model_name='maquinaria',
            old_name='MARCA',
            new_name='marca',
        ),
        migrations.RenameField(
            model_name='maquinaria',
            old_name='ORDEN',
            new_name='orden',
        ),
        migrations.RenameField(
            model_name='maquinaria',
            old_name='PROBLEMA',
            new_name='problema',
        ),
    ]
