# Generated by Django 4.2.6 on 2023-11-24 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_rename_año_manual_manual_año_manual_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='cargo',
            field=models.CharField(default='cargo', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='direccion',
            field=models.CharField(default='direccion', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='rut',
            field=models.CharField(default='2000000', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='siglas',
            field=models.CharField(default='AA', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='telefono',
            field=models.CharField(default='Telefono', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='12334', max_length=100),
            preserve_default=False,
        ),
    ]
