# Generated by Django 4.2.6 on 2023-11-18 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_rename_name_user_cargo_user_direccion_user_rut_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquinaria',
            name='numero_serie',
            field=models.CharField(default='H001', max_length=100),
            preserve_default=False,
        ),
    ]
