# Generated by Django 4.2.6 on 2023-12-10 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_maquinaria_numero_serie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trazabilidad',
            old_name='año',
            new_name='año_trazabilidad',
        ),
        migrations.RenameField(
            model_name='trazabilidad',
            old_name='cliente',
            new_name='cliente_trazabilidad',
        ),
        migrations.RenameField(
            model_name='trazabilidad',
            old_name='descripcion_problema',
            new_name='descripcion_problema_trazabilidad',
        ),
        migrations.RenameField(
            model_name='trazabilidad',
            old_name='fecha',
            new_name='fecha_trazabilidad',
        ),
        migrations.RenameField(
            model_name='trazabilidad',
            old_name='maquinaria',
            new_name='maquinaria_trazabilidad',
        ),
        migrations.RenameField(
            model_name='trazabilidad',
            old_name='marca',
            new_name='marca_trazabilidad',
        ),
        migrations.RenameField(
            model_name='trazabilidad',
            old_name='n_orden',
            new_name='n_orden_trazabilidad',
        ),
        migrations.AlterField(
            model_name='maquinaria',
            name='orden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.trazabilidad'),
        ),
    ]
