# Generated by Django 4.2.6 on 2023-12-10 13:47

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_user_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquinaria',
            name='orden',
            field=models.CharField(default=myapp.models.generar_numero_aleatorio, max_length=100),
        ),
        migrations.AlterField(
            model_name='trazabilidad',
            name='n_orden_trazabilidad',
            field=models.CharField(max_length=100),
        ),
    ]
