# Generated by Django 4.2.6 on 2023-12-10 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_maquinaria_fecha_creacion_m_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='orden',
            field=models.CharField(default='AA02218596', max_length=100),
            preserve_default=False,
        ),
    ]
